### ISSUE TITLE
Parse error when trying to extend script with declared class_name

### ISSUE THREAD

**Issue by aesereht** [GodotModding/godot-mod-loader#406] opened 2024-08-15 19:43 UTC
Maybe related with https://github.com/GodotModding/godot-mod-loader/issues/338
![image](https://github.com/user-attachments/assets/b2c60ebb-9891-40b0-9150-526346b9a728)
When trying to extend script with it produce errors. The example above was when trying to extend the `_ready()` method .

In case of just adding the code even without execution it will also produce error
```godot
func test():
	print("test")
```
![capture](https://github.com/user-attachments/assets/b87c1a98-a8fa-4475-952a-0cccc8eb4e76)
where the script that produce error is not connected to extended script
`MultiplayerloadoutStage.gd` was the extended script while `GameWorld.availableTechSlots.duplicate()` produced error
`GameWorld` is a singleton

`MultiplayerloadoutStage.gd` first lines
```godot
extends Stage
class_name MultiplayerLoadoutStage
...
```

**Comment by ZackeryRSmith** [comment] 2024-09-02 14:48
Duplicate of #345

**Closed by ZackeryRSmith** 2024-09-02 14:48 UTC
Labels: 4.x
