### ISSUE TITLE
can't extend or overwrite .gd files that have custom class_name

### ISSUE THREAD

**Issue by lafitteque** [GodotModding/godot-mod-loader#417] opened 2024-10-22 05:27 UTC
Hello,
I'm learning how to use mod-loader and I'm faced with this issue when moding Dome Keeper 4.1 . When extending or overwriting a file such as Tile.gd or Map.gd or MapData.gd, the following error occurs : Class "Tile" hides a global script class.
When removing "class_name Tile" from the original file, the extension works. The same issue stands for custom ressources.

Is there a way around this whithout creating conflicts with other mods?

**Comment by KANAjetzt** [comment] 2024-10-22 20:05
Hi, currently there is no fix for this issue. We are in the process of creating an entirely new approach for extending scripts. You can follow the progress [here](https://github.com/GodotModding/godot-mod-loader/pull/408).

I'm closing this as it is a duplicate of an existing issue. For Dome Keeper specific help, I recommend joining [the Bippinbits Discord](https://discord.gg/AxYpX7AaFP), and I'd be happy to chat over there.

- https://github.com/GodotModding/godot-mod-loader/issues/345

**Closed as not planned by KANAjetzt** 2024-10-22 20:05 UTC
Labels: bug, duplicate, 4.x
