### ISSUE TITLE
append_node_in_scene order

### ISSUE THREAD

**Issue by aesereht** [GodotModding/godot-mod-loader#236] opened 2023-04-24 23:01 UTC
```go
append_node_in_scene(modified_scene, node_name, node_parent, instance_path, is_visible)

func appendNodeInScene(
	# an instanced scene of a PackedScene you want to replace
	modified_scene:Scene, 

	# name of the new node
	node_name:String = "", 

	# path to the parent node in the PackedScene
	node_parent = null, 

	# path used to instanciate the node
	instance_path:String = "", 

	# node visibility state
	is_visible:bool = true
)
```
Not sure how the method works, but if we would follow the method name it should be able to append Node to Scene, but even if there is a parent node option, it's lacking the option to add order

```go
extends "res://systems/options/OptionsPanel.gd"                       # Mod loader api method to extend original script

func _ready():                                                        # _ready is funny function you cant modify it
                                                                      ### but you can run it multiple times
    var node = Button.new()                                           # creating new button
    node.text = "Close"                                               # Adding text to button
    node.connect("pressed", self, "_on_ButtonCancel_pressed_test")    # Connecting (pressing) button with function
    $PanelContainer/VBoxContainer/CategoriesList.add_child(node)      # Adding button to list
    $PanelContainer/VBoxContainer/CategoriesList.move_child(node, 0)  # Moving button position to 1
    Style.init(self)                                                  # Applying the style to button

func _on_ButtonCancel_pressed_test()->void :                          # Custom button function
    ._on_ButtonCancel_pressed()                                       # Calling in game function
    emit_signal("close")                                              # Using signal to close window
```
Here is an example with appending node (and creating it) and after that moving it to position using the extend_script method

I dont know if it would be button specific, but in case of Dome Keeper I think it's better to create all buttons by script if editing original scene as it should be more cross mod compatible.

**Comment by KANAjetzt** [comment] 2023-10-04 13:19
closing this - duplicate of #4

**Closed by KANAjetzt** 2023-10-04 13:19 UTC
Labels: duplicate
